apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  endpoints:
    - port: http
      interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
