{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysecretbox",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysecretbox",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "ACCESS_TOKEN_SECRET": "AgAOxaH4yuOnuePpDMC93GyWAVT6cLkJGjT/Ymo5viV30KdN3vn7L4T/FoOutupMpn349g9MZIFO2fKVaeeLRNswl5ZxGfWeRAY91ZKi40K8kkT+ZE1xvLYkxbU3Ll4EIZMlkpfrBdO8fJXePew6newa2X5pDJdQb5I9jxJ/VUz+247uvCs32chhJzBOrEsJi8nUZx7L1h/rjbvsAMQjmAmhQqhANuNlKKOUzaRgnHSW14Q9wHzaSnOiV+/Fpvns7BanRvfaSEQNWKi+jtCFApsrZB8ut4mGn6k5aKbo95hWQ86RZ8aJuAjMG2C0HLPNQavOpMPDsnkqhlHNv/ku/SXXq7DGNRQCFe3Vpwc2rPixpVUvqFYfDZ5GNQqftcH9Z/I4UxhPiC2DSCnySw6JOUjwzyzExMO+gcjhtOvQyebnOPpWa0kQwA8swvnm8R2kb7Ddt9oQwhHE+0h5gWb4VNZqaEktbiCOyyPNbqnHWkzfvyaX8fOzQ1SjyxdMNipVwRy0Xh9kHlp2pvLp3dqKdT9gx5rlUdNWE4yY1BMAhc3fFbToxkqmGnP8tP5aVh0AcJ5em6gWRS78vVvGaXOR8umksCIF20l7ZVyUw2Uqp2I7hy4QFnvpdpKlMKxUPYIiaqMpQO+4Wik1L21zo3P2rKLsDZGZ5uVlk1Ac5BLRJ6nm+cwQYPQ6NyWLi3qxj+SNHAJGk95ykQx1bW72rHPV0ku5lER8U6movPAcAi3YYTgH9kSsMpaWHCorJdi8mPnCtROMVP3XsXCZW5Vi",
      "JWT_SECRET": "AgAhXv0GTWmRcCLzJNnYgpVXYWFc8JklNO5xy7hEq74BQOBTc3B2wgiE2pO6cd+LkcXncjosG2gMUhoGL2O3+Lq9DPViAiCTxcTg9rouUbV+03S8Cg11dv4XW1oDZd8V30UDVZQilgzmQCzkoDfWim/PMqucAgwK8qexDQ/PXkhqxc4uv4xSUv9CwNJLs99gL0Pef9Mi13KW1jm8BEVEp34Lw5Btdn2uj7VX7ZWrCdASr6ROPtOnDpFLPv2SPRFz5yNTNi4dRHoipMDe9nh5mL5gw/c3eWcgCW/7hDJS1XcunZ5Sl4AAZJjqDdL4ByJN3TX8ZbOJHAzSYM4ZaFdit0QShyOuw6UkvbQawjRHvUsymEm4Qyp4ia1VbB0frMcZQzOrFCzUrtW5LIzI0KXhO+aDFTt6OmoR4aNCn08XTABekaOhxKjou0Py3IF9jAbmhL+n73oXUuHKgpYXITR04uVlajSkSw9wayIwfva3GRMTd4r7+7X/TDTtUxCusWe7cXCqQqnm5h1ZHWUu/uVPF6hY9KKXmIIy0U9UHb7Q4IiLMQLNABRyJaBIpNr2Hm96Rplg4jX0qPYBMKjboeemgk7fm2NjWqR50yRhvmaCLAHoZFL9YnngFnje+YpF9sigG2Hgxp1XUiAeym+QckPwEf0ZT24VgXhv7antQa3Ual1FqfCJf2kztaYhQ7Vxj6nn5sa4nti3Ep7JCPaHZ8kwuyoFmNHAbN6F0zYPuh4VPZoiZ7+72L40uyfnsUXZNJHuThb2c14zhA==",
      "MONGODB_URI": "AgCXfgP4k2dKbuqERYIsqrbVRu3K8C9u+6N+PbXqcIl13eZ4BbXwYjaWlgrM0Z5imzLzKODofzopmSpYHwdQIyke+MDFPV09xpAvKe2es9SbpNH9dprABi63k5Y/qvlpA0PMn5wIleA7BNTTN5Ugppc9ou3O3DKDg61t5Xujke0gkWJWjMQCcsFebWbOqPK6oAorNJCgIMcF/EyDwaLLTZitgVw3DqiOHi43pWDEzNTSYbbfD1EIfRadjbU+xlEo1fHA/kYNwzqbO3n+RmJrRNomzfO6c/gRAXwwzCAAtXq8qu/f/AgbPVqyUc+nD1soTnjYYbrJMtSsNp1P9n33qc751azMXVdBx7FStcnAAf6CmTnTM4KsRkWY7ePqsTr8NLqlu2Bsucuj26e7MRZQ2L2V5F89na+OgQQbYmgGOUfFRisUC1z0mhIUluDj+DIXXGryGKaELfYxNfNqik/eUaF139yjVkzMKP+Ab85K1BwiOSGunJJ0GmAblhu3xc2ailYspilRKlUM9Vl6IXIXl0buChn+A5odp+zpv66wwzbocc9Fzng2jxP1pHUjglVtrMHZ39Iv+ldf/fPfAiyEfqs+hj7h5p2mlXDEV/qILeLtb2EvhmulZl7RjFczjrG5OTAZAZuS0ZNj/kVRQi9VWQwnCLzjsxSXa/lAVoWMa8CJXIINYDfsxVzIn+WvQkmdCvbx9cYrt62xZuDB4cxXekHozHi6FMdgis/qPzxcijkCFx8YlkC6QNuEF2AwN+RZSVpRAHSDFgmLdyIm2Q=="
    }
  }
}
