apiVersion: v1
kind: Secret
metadata:
  name: mysecretbox
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly96cmRyYzMxOmt1bmFsMTIzQGNsdXN0ZXIwLmFiaTNtYzMubW9uZ29kYi5uZXQ=
  ACCESS_TOKEN_SECRET: a2Fqc2hpdXdlYnJiMjlrYXNkamZpdWF3ZWtqYndranpibWN6dmpraHVrempza2J2eGpjYnZpYXNkZg==
  JWT_SECRET: a2Fqc2h1d2VicmIyOWthc2Rqa3NqaGRmdWhhc3V5ZGFnZm9pdXdlYnJiMjlrYXNkamtzZGo=
